- name: base.repos | user-vagrant-repos.yml | Clone base repo's
  file:
    path: /home/vagrant/working/go/src/{{ item.directory }}
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0755
  with_items:
    - { directory: "github.com/hashicorp" }

- name: base.repos | user-vagrant-repos.yml | Git clone {{ item }}
  git:
    repo: https://git@github.com/hashicorp/{{ item }}.git
    dest: /home/vagrant/working/go/src/github.com/hashicorp/{{ item }}
  become: yes
  become_user: vagrant
  with_items:
    - vault
    - terraform
    - packer
    - consul
