- name: base.packages | install-packages | install base packages for system
  package: name={{ packages }} state=latest update_cache=yes

- name: base.packages | install-packages | install base snaps for system
  command: snap install {{ item }} --classic
  with_items:
    - go
    - kubeadm
    - kubectl
    - helm
    - postman

