- name: base.packages | install-packages | install base packages for system
  package: name={{ item }} state=latest update_cache=yes
  with_items:
    - vim
    - tmux
    - sysstat 
    - net-tools
    - curl
    - sysdig
    - htop
    - composer
    - build-essential
    - git
    - gnupg
    - golang
    - golang-go
    - jq
    - lxd
    - nmap
    - netcat-openbsd
    - nodejs
    - npm
    - openvpn
    - p7zip
    - php7.2-cli
    - php7.2-common
    - php7.2-curl
    - php7.2-json
    - php7.2-mbstring
    - php7.2-opcache
    - php7.2-readline
    - php7.2-bcmath
    - php7.2-xml
    - php7.2-intl
    - php7.2-phpdbg
    - pv
    - rar
    - rsync
    - socat
    - sqlite3
    - tor
    - tree
    - unrar
    - whois
    - xxd
    - zlib1g
    - zlib1g-dev
