- name: base.packages | main | Sleep for apt to settle
  wait_for:
    timeout: 30
  tags: ["install","dist-upgrade"]
  
- name: base.packages | main | Distribution upgrade 
  include_tasks: dist-upgrade.yml
  tags: ["install","dist-upgrade"]

- name: base.packages | main | Install packages
  include_tasks: install-packages.yml
  tags: ["install"]

#- name: base.packages | main | Install go
#  include_tasks: install-go.yml
#  tags: ["install", "go"]
