name: "Build Vagrant"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ * ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#    - name: Install packages
#      run: |
#        sudo apt-get update
#        sudo apt-get -y install vagrant virtualbox-dkms xvfb
    - name: Checkout local repo
      uses: actions/checkout@v2 
    - name: Checkout boxcutter repo
      uses: actions/checkout@v2
      with:
        repository: boxcutter/ubuntu 
        path: ubuntu
    - name: Init git submodules
      run: |
        git submodule update --init --recursive
    - name: Copy boxcutter ubuntu templates
      run: |
        cp -a boxcutter/ubuntu2004-desktop.json ubuntu/
        cp -a boxcutter/tpl/vagrantfile-ubuntu2004-desktop.tpl ubuntu/tpl/
    - name: Validate packer files
      run: |
        PACKER_LOG=10 packer validate -syntax-only -var-file="boxcutter/ubuntu2004-desktop.json" boxcutter/ubuntu.json
#    - name: Build vagrant
#      uses: rkialashaki/setup-vagrant@0.0.1-alpha
#      with:
#        exec: |
#          vagrant up
##      run: |
##        script
##        cd ubuntu
##        PACKER_LOG=10 xvfb-run packer build -debug -only=virtualbox-iso -var-file=ubuntu2004-desktop.json ubuntu.json
##    - name: Build vagrant
##      run: |
##          vagrant box add --name ubuntu-rk/2004-desktop box/virtualbox/ubuntu2004-desktop-0.1.0.box
##          vagrant up
###    - name: Use oxr463/setup-vagrant
