name: "Build Vagrant"

on:
  push:
    branches: [ ub2004 ]
  pull_request:
    branches: [ ub2004 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get -y install vagrant virtualbox xfce4 slim
        sudo service slim start
    - name: Checkout local repo
      uses: actions/checkout@v2 
    - name: Checkout boxcutter repo
      uses: actions/checkout@v2
      with:
        repository: boxcutter/ubuntu 
        path: ubuntu
    - name: Copy boxcutter ubuntu templates
      run: |
        cp -a boxcutter/ubuntu2004-desktop.json ubuntu/
        cp -a boxcutter/tpl/vagrantfile-ubuntu2004-desktop.tpl ubuntu/tpl/
    - name: Build packer box
      run: |
        cd ubuntu
        packer build -debug -only=virtualbox-iso -var-file=ubuntu2004-desktop.json ubuntu.json
    - name: Build vagrant
      run: |
          vagrant box add --name ubuntu-rk/2004-desktop box/virtualbox/ubuntu2004-desktop-0.1.0.box
          vagrant up
#    - name: Use oxr463/setup-vagrant
#      uses: oxr463/setup-vagrant@0.0.1-alpha
#      with:
#        exec: |
#          vagrant box add --name ubuntu-rk/2004-desktop box/virtualbox/ubuntu2004-desktop-0.1.0.box
#          vagrant up
